spring:
  application:
    name: product-service
  profiles:
    active:
    - dev
  main:
    allow-bean-definition-overriding: true  
server:
  port: 9071
  servlet:
    context-path: /product-service

         